[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#F63366"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#9A752C"
textColor = "#FAFAFA"
borderColor = "white"
baseRadius = "full"
showWidgetBorder = true
font = "calibri"

[theme.sidebar]
base = "dark"
primaryColor = "red"